[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "tmscraper"
author = "Marcus Croucher"
author-email = "timbledum@gmail.com"
home-page = "www.google.com"
classifiers = ["License :: OSI Approved :: MIT License"]

